### ISSUE TITLE
IllegalAccessException

### ISSUE THREAD

**Issue by BGHDDevelopment** [iiAhmedYT/ModernDisguise#7]
Hey all!

Saw this and wanted to try it out. Seems like an excellent library.
Though I am getting this on the latest version while running Spigot 1.20.1.

The DisguiseResponse still returns SUCCESS, though no actual disguise takes place. Same with undisguise.

Command code:
https://pastebin.com/v5X2AfSs
Loading code:
https://pastebin.com/rZe0yATK

If you have any ideas would be happy to try them.

- Stephan

```
java.lang.IllegalAccessException: class dev.iiahmed.disguise.DisguiseUtil cannot access a member of class net.minecraft.server.level.EntityPlayer with modifiers "private static final"
[08:42:36 WARN]: 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
[08:42:36 WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
[08:42:36 WARN]: 	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
[08:42:36 WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:423)
[08:42:36 WARN]: 	at Core2023.jar//dev.iiahmed.disguise.DisguiseUtil.getChannel(DisguiseUtil.java:309)
[08:42:36 WARN]: 	at Core2023.jar//dev.iiahmed.disguise.DisguiseUtil.inject(DisguiseUtil.java:275)
[08:42:36 WARN]: 	at Core2023.jar//dev.iiahmed.disguise.listener.PlayerListener.onJoin(PlayerListener.java:24)
[08:42:36 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source)
[08:42:36 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[08:42:36 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[08:42:36 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:42:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[08:42:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[08:42:36 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[08:42:36 WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:339)
[08:42:36 WARN]: 	at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[08:42:36 WARN]: 	at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[08:42:36 WARN]: 	at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[08:42:36 WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:602)
[08:42:36 WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[08:42:36 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1602)
[08:42:37 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[08:42:37 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1409)
[08:42:37 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1186)
[08:42:37 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[08:42:37 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by iiAhmedYT** [comment]
Ah the untested version fireback at me
I'll work on it for tonight, Thank you so much for reporting this error!

**Comment by iiAhmedYT** [comment]
Seems to be fixed now, enjoy! let me know if you have any problems (i'll publish this version is less than an hour)

**Comment by BGHDDevelopment** [comment]
Hey! So this does work correctly now, though I am getting kicked when trying to type while nicked/disguised for "Chat message validation failure." While you add the RESET to disable that check, do I need to do anything inside my plugin to further disable? Never messed with this system before.

**Comment by iiAhmedYT** [comment]
Not really. the thing is i don't have that issue? can i know what software you're testing your plugin on? and what java version please?

**Comment by BGHDDevelopment** [comment]
Java 17, paper 1.20.1 (also tried normal buildtools spigot 1.20.1), only happening when disguised and typing something in chat. I am researching other possible causes as well.

**Comment by iiAhmedYT** [comment]
I'm looking into it but it could take me sometime. Can you please use a different plugin to block mojang's verification thing for now?

**Comment by iiAhmedYT** [comment]
Hello, I'm working on a fix for the Chat Message validation issue and I have found this method that works just fine if your plugins are using the spigot api in a correct way

![image](https://github.com/iiAhmedYT/ModernDisguise/assets/61851106/5f0fa461-c168-4a53-bd7a-735c3a13f7ba)
